package moark

import "github.com/QuantumNous/new-api/constant"

var ModelList = []string{
	// Chat / completions examples from Moark OpenAPI.
	"Qwen3-235B-A22B-Instruct-2507",
	"Qwen3-Coder-30B-A3B-Instruct",
	"Qwen3.7-Plus",
	"DeepSeek-V3",
	"DeepSeek-R1",
	"Kimi-K2.5",
	"Kimi-K2.6",
	"GLM-5.2",
	"GLM-5.1",
	"MiniMax-M3",
	"gpt-oss-120b",
	// Moderations.
	"moark-text-moderation",
	"Security-semantic-filtering",
	"nonescape-v0",
	"nsfw-classifier",
	// Embeddings and rerank.
	"Qwen3-Embedding-0.6B",
	"jina-clip-v1",
	"jina-clip-v2",
	"jina-embeddings-v4",
	"bge-m3",
	"Qwen3-VL-Embedding-8B",
	"all-mpnet-base-v2",
	"Qwen3-Embedding-8B",
	"Qwen3-VL-Embedding-2B",
	"bce-embedding-base_v1",
	"bge-small-zh-v1.5",
	"Qwen3-Embedding-4B",
	"bge-large-zh-v1.5",
	"bce-reranker-base_v1",
	"Qwen3-Reranker-0.6B",
	"Qwen3-Reranker-4B",
	"bge-reranker-v2-m3",
	"Qwen3-Reranker-8B",
	// Native async task routing.
	constant.MoarkTaskModel,
	// Documents / OCR.
	"PDF-Extract-Kit-1.0",
	"MinerU2.5",
	"DeepSeek-OCR",
	"PaddleOCR-VL-1.5",
	"PaddleOCR-VL",
	// Video / 3D / audio / music / image async endpoints.
	"happyhorse-1.1",
	"Wan2.7",
	"ViduQ3-Turbo",
	"Wan2.1-T2V-14B",
	"HunyuanVideo-1.5",
	"HappyHorse-1.0",
	"ViduQ2-Turbo",
	"ViduQ2-Pro",
	"ViduQ3-Pro",
	"LTX-2",
	"Wan2_2-I2V-A14B",
	"InfiniteTalk",
	"Duix.Heygem",
	"TeleASR-MultiDialect",
	"IndexTTS-2",
	"Spark-TTS-0.5B",
	"AudioFly",
	"Qwen3-TTS",
	"CosyVoice3",
	"FLUX.1-dev",
	"FLUX.2-klein-4B",
	"Kolors",
	"GLM-Image",
	"qwen-image-2.0",
	"z-image-turbo",
	"stable-diffusion-3.5-large-turbo",
	"LongCat-Image",
	"flux-1-schnell",
	"Qwen-Image-2512",
	"stable-diffusion-xl-base-1.0",
	"Z-Image",
	"Qwen-Image",
	"HiDream-I1-Full",
	"FLUX.2-dev",
	"CogView4_6B",
	"stable-diffusion-3-medium",
	"FLUX.2-klein-9B",
	"FLUX_1-Krea-dev",
	"DreamO",
	"LongCat-Image-Edit",
	"Qwen-Image-Edit",
	"Qwen-Image-Edit-2511",
	"AnimeSharp",
	"FLUX.1-Kontext-dev",
}

var ChannelName = "模力方舟"
